# Generated by Django 5.0.2 on 2024-02-15 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salon', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PetAndUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='pet', to='Salon.pet')),
                ('user', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('master', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='Salon.employee')),
                ('pet_user', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='Salon.petanduser')),
                ('service', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='Salon.service')),
            ],
        ),
    ]
