# Generated by Django 5.0.2 on 2024-02-15 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Salon', '0002_petanduser_record'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Грумер', 'verbose_name_plural': 'Грумеры'},
        ),
        migrations.AlterModelOptions(
            name='pet',
            options={'verbose_name': 'Питомец', 'verbose_name_plural': 'Питомцы'},
        ),
        migrations.AlterModelOptions(
            name='petanduser',
            options={'verbose_name': 'Клиент и питомец', 'verbose_name_plural': 'Клиенты и питомцы'},
        ),
        migrations.AlterModelOptions(
            name='record',
            options={'verbose_name': 'Запись', 'verbose_name_plural': 'Записи'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
    ]
