# Generated by Django 5.0.2 on 2024-02-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salon', '0003_alter_employee_options_alter_pet_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='photo',
            field=models.ImageField(blank=True, default='', upload_to='pets'),
        ),
    ]
