# Generated by Django 5.0.2 on 2024-02-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salon', '0005_alter_record_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='status',
            field=models.CharField(default='Заявка принята', max_length=50),
        ),
    ]
