# Generated by Django 5.0.2 on 2024-02-20 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salon', '0006_alter_record_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='time',
            field=models.CharField(choices=[('9', '09:00'), ('10', '10:00'), ('11', '11:00'), ('12', '12:00'), ('13', '13:00'), ('14', '14:00'), ('15', '15:00'), ('16', '16:00'), ('17', '17:00')], max_length=50),
        ),
    ]
