# Generated by Django 5.0.2 on 2024-02-20 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salon', '0008_typeanimal_alter_record_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Salon.typeanimal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Salon.typeanimal'),
            preserve_default=False,
        ),
    ]
