# Generated by Django 5.0.2 on 2024-02-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salon', '0009_pet_type_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='status',
            field=models.CharField(choices=[('1', 'Заявка принята в обработку'), ('2', 'Заявка обрабатывается'), ('3', 'Заявка принята')], max_length=50),
        ),
    ]
