# Generated by Django 5.0.2 on 2024-04-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salon', '0010_alter_record_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, default='', upload_to='groomers'),
        ),
    ]
