# Generated by Django 5.0.2 on 2024-04-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salon', '0011_employee_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='about',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
