# Generated by Django 5.0.2 on 2024-04-30 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salon', '0012_employee_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_race', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='record',
            name='status',
            field=models.CharField(choices=[('1', 'Заявка принята в обработку'), ('2', 'Заявка обрабатывается'), ('3', 'Заявка принята'), ('4', 'Заявка выполнена')], max_length=50),
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='', upload_to='')),
                ('description', models.TextField(max_length=250)),
                ('employee', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='Salon.employee')),
            ],
        ),
    ]
