# Generated by Django 5.0.2 on 2024-05-13 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salon', '0014_alter_pet_race'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name': 'Портфолио', 'verbose_name_plural': 'Портфолио'},
        ),
        migrations.AlterModelOptions(
            name='race',
            options={'verbose_name': 'Порода', 'verbose_name_plural': 'Породы'},
        ),
        migrations.AddField(
            model_name='race',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Salon.typeanimal'),
        ),
        migrations.AlterField(
            model_name='record',
            name='status',
            field=models.CharField(choices=[('1', 'Ожидание подтверждения'), ('2', 'Запись подтверждена'), ('3', 'Выполнена')], max_length=50),
        ),
    ]
