# Generated by Django 5.0.2 on 2024-05-13 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Salon', '0015_alter_portfolio_options_alter_race_options_race_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='type',
        ),
    ]
